package firewall

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
)

type FirewallManager struct {
	mu           sync.Mutex
	ruleFilePath string
}

func NewFirewallManager(ruleFilePath string) *FirewallManager {
	if ruleFilePath == "" {
		ruleFilePath = "/etc/nftables.d/12-mangle-qmanager-dpi.nft"
	}
	return &FirewallManager{
		ruleFilePath: ruleFilePath,
	}
}

// GenerateDPIRules generates nftables mangle chain rules for NFQUEUE DPI packet inspection
func (fm *FirewallManager) GenerateDPIRules(enabled bool, queueNum int, ttlVal int) string {
	var sb strings.Builder
	sb.WriteString("# Generated by QManager Go Native Firewall Manager\n")
	sb.WriteString("table inet mangle {\n")
	sb.WriteString("  chain qmanager_dpi {\n")
	sb.WriteString("    type filter hook postrouting priority mangle; policy accept;\n")

	if enabled {
		if queueNum <= 0 {
			queueNum = 200
		}
		sb.WriteString(fmt.Sprintf("    tcp dport { 80, 443 } queue num %d bypass;\n", queueNum))
	}

	if ttlVal > 0 {
		sb.WriteString(fmt.Sprintf("    ip ttl set %d;\n", ttlVal))
		sb.WriteString(fmt.Sprintf("    ip6 hoplimit set %d;\n", ttlVal))
	}

	sb.WriteString("  }\n")
	sb.WriteString("}\n")
	return sb.String()
}

func (fm *FirewallManager) SaveRules(enabled bool, queueNum int, ttlVal int) error {
	fm.mu.Lock()
	defer fm.mu.Unlock()

	content := fm.GenerateDPIRules(enabled, queueNum, ttlVal)
	dir := filepath.Dir(fm.ruleFilePath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return err
	}

	return os.WriteFile(fm.ruleFilePath, []byte(content), 0644)
}

func (fm *FirewallManager) GetRuleFilePath() string {
	return fm.ruleFilePath
}
